# Generated by Django 3.0.5 on 2024-02-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PARENT',
            fields=[
                ('PARENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('PHONE_NO', models.CharField(max_length=255)),
                ('EMAIL_ADDRESS', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TEACHER',
            fields=[
                ('TEACHER_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('PHONE_NO', models.CharField(max_length=255)),
                ('EMAIL_ADDRESS', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TEACHER_INFO',
            fields=[
                ('TEACHER_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ATS_app.TEACHER')),
                ('DEPARTMENT', models.CharField(max_length=255)),
                ('SECTION', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('STUDENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('PARENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS_app.PARENT')),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT_INFO',
            fields=[
                ('STUDENT_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ATS_app.STUDENT')),
                ('DEPARTMENT', models.CharField(max_length=255)),
                ('SECTION', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SUBJECT',
            fields=[
                ('SUBJECT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('SUBJECT_NAME', models.CharField(max_length=255)),
                ('TEACHER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS_app.TEACHER')),
            ],
        ),
        migrations.CreateModel(
            name='ATTENDANCE',
            fields=[
                ('ATTENDANCE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DATE', models.DateField()),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS_app.STUDENT')),
            ],
        ),
        migrations.CreateModel(
            name='ATTENDANCE_PER_HRS',
            fields=[
                ('ATTENDANCE_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ATS_app.ATTENDANCE')),
                ('HOUR', models.IntegerField()),
                ('STATUS', models.CharField(max_length=255)),
                ('SUBJECT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS_app.SUBJECT')),
                ('TEACHER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS_app.TEACHER')),
            ],
        ),
        migrations.CreateModel(
            name='ATTENDANCE_INFO',
            fields=[
                ('ATTENDANCE_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ATS_app.ATTENDANCE')),
                ('ABSENCE_REASON', models.CharField(max_length=255)),
                ('OD_REASON', models.CharField(max_length=255)),
                ('LATE_REASON', models.CharField(max_length=255)),
            ],
        ),
    ]
