# Generated by Django 3.0.5 on 2024-02-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_per_hrs',
            name='ATTENDANCE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ATS_app.ATTENDANCE'),
        ),
    ]
