# Generated by Django 5.0.2 on 2024-04-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_data',
            name='STUDENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS_app.student'),
        ),
        migrations.AddField(
            model_name='attendance_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        
    ]
