# Generated by Django 5.0.2 on 2024-04-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_data',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='STUDENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS_app.student'),
        ),
    ]
