# Generated by Django 3.0.5 on 2024-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_app', '0002_auto_20240220_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_info',
            name='TEACHER_ID',
        ),
        migrations.RemoveField(
            model_name='attendance_per_hrs',
            name='TEACHER_ID',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='TEACHER_ID',
        ),
        migrations.AddField(
            model_name='subject',
            name='DEPARTMENT',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ATTENDANCE_INFO',
        ),
        migrations.DeleteModel(
            name='TEACHER',
        ),
        migrations.DeleteModel(
            name='TEACHER_INFO',
        ),
    ]
