# Generated by Django 5.0.2 on 2024-03-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_app', '0003_auto_20240224_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEACHER',
            fields=[
                ('TEACHER_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('PHONE_NO', models.CharField(max_length=255, unique=True)),
                ('EMAIL_ADDRESS', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='EMAIL_ADDRESS',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='EMAIL_ADDRESS',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='PHONE_NO',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
